name: Sync to Tester Repository

on:
  push:
    branches:
      - main # Trigger on push to main branch in Developer repository

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Developer Repository
      - name: Checkout Developer Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      # Step 2: Set up Git user
      - name: Configure Git User
        run: |
          git config --global user.name "Sneha781"
          git config --global user.email "snehalatha.ikutti@qwikspark.com"

      # Step 3: Clone Tester Repository
      - name: Clone Tester Repository
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN111 }}@github.com/Sneha781/tester.git /tmp/testing-repo

      # Step 4: Sync Files
      - name: Sync Files to Tester Repository
        run: |
          rsync -av --delete ./ /tmp/testing-repo/ --exclude .git
          cd /tmp/testing-repo
          git status

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          cd /tmp/testing-repo
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping push."
          else
            git commit -m "Auto-sync: Updating from Developer repository"
            git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN111 }}@github.com/Sneha781/tester.git main
          fi

            git commit -m "Auto-sync: Updating from Developer repository"
            git push origin main
          fi
