name: Trigger Tester Repository

on:
  push: # Trigger on every push
    branches:
      - main

jobs:
  notify-tester:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Tester Repository
        run: |
          curl -X POST -H "Authorization: token <GITHUB_PERSONAL_ACCESS_TOKEN>" \
          -d '{"event_type": "run-tests"}' \
          https://api.github.com/repos/<Sneha781>/<test-run>/dispatches
