name: Trigger Tester Repository

on:
  push:  # Trigger on push events
    branches:
      - main  # Or any branch you'd like to monitor

jobs:
  notify-tester:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Tester Repository Workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN111 }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type": "run-tests"}' \
          https://api.github.com/repos/OWNER/tester/dispatches
