name: Trigger Tester Repository

on:
  push:
    branches:
      - main  # Trigger on push to the main branch of the current repository

jobs:
  notify-tester:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Tester Repository
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN11 }}" \
          -d '{"event_type": "run-tests"}' \
          https://api.github.com/repos/Sneha781/test-run/dispatches

